### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by HarpyWar** [cdhowie/Eluant#3]
Is it possible to handle .NET events in Lua script?

**Comment by cdhowie** [comment]
I'm not aware of anything preventing you from handling events, but there is currently no automatic mechanism by which Lua can subscribe to events on a transparent CLR object.  Any sort of transparent event binding provided by Eluant would be complicated by handling of the event arguments (sender and args), which may not be directly proxy-able.

However, nothing prevents you from implementing your own mechanism.  There are a few caveats though.  Eluant may someday provide a generalized version of an event watch/unwatch pattern for C# events, but it will require solving a few design issues.

**Comment by HarpyWar** [comment]
Could you give a simple example of the implementation? For example I have a chat client and I want to subscribe on a text message event in lua script.

**Comment by cdhowie** [comment]
The easiest way right now would be to expose a `watch_message()` function/method that accepts a `LuaFunction`.  You would subscribe to the event on the C# side, and convert the data to a `LuaTable` passing this to the function.

The tricky part is how to unsubscribe from the event.  You can't simply provide `unwatch_message()` that accepts the same Lua function, because the two `LuaFunction` objects would not be the same, nor would they have the same reference identifier -- they would not compare as equal.  There are two ways I can think of that you could use to overcome this problem:
1. Return a token object from `watch_message()`, which the Lua code could later pass to `unwatch_message()`.  This token object would be used to look up the `LuaFunction` object on the C# side.
2. Return a function (or object with a function) from `watch_message()` that would unsubscribe that particular listener when called.

For example, you might do something like this, which uses the first approach given above (code is not tested!).  You could potentially abstract this code into a general class that could be shared for many different events.

```
public event ChatMessageEventHandler ChatMessage;

private Dictionary<object, LuaFunction> chatMessageLuaWatchers =
    new Dictionary<object, LuaFunction>();

private LuaTable ToLuaTable(ChatMessageEventArgs args)
{
    var table = luaRuntime.CreateTable();

    try {
        // Do whatever conversion you need to here.
    } catch {
        table.Dispose();
        throw;
    }

    return table;
}

protected virtual void OnChatMessage(ChatMessageEventArgs args)
{
    var h = ChatMessage;
    if (h != null) { h(this, args); }

    lock (chatMessageLuaWatchers) {
        foreach (var fn in chatMessageLuaWatchers.Values) {
            using (var table = ToLuaTable(args)) {
                fn.Call(table).Dispose();
            }
        }
    }
}

[LuaMember]
public LuaOpaqueClrObject watch_message(LuaFunction fn)
{
    if (fn == null) { throw new LuaException("Argument must not be nil."); }

    var token = new object();

    lock (chatMessageLuaWatchers) {
        chatMessageLuaWatchers[token] = fn;
    }

    return new LuaOpaqueClrObject(token);
}

[LuaMember]
public void unwatch_message(object token)
{
    lock (chatMessageLuaWatchers) {
        LuaFunction fn;

        if (chatMessageLuaWatchers.TryGetValue(token, out fn)) {
            chatMessageLuaWatchers.Remove(token);
            fn.Dispose();
        }
    }
}
```
